language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-simple' ]; then cd .. && eval "mv $currentfolder generator-simple" && cd generator-simple; fi

